### ISSUE TITLE
Dependency jeremeamia/superclosure is abandoned

### ISSUE THREAD

**Issue by micschk** [silverstripe/doorman#35]
Composer warns that:
```Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.```

### Aceptance criter
- [ ] new package is tested alongside queuedjobs functionality
- [ ] existing PR is merged
- [ ] queuedjobs receives a change to pull in the new version of the doorman module, see: https://github.com/symbiote/silverstripe-queuedjobs/issues/343

**Comment by madmatt** [comment]
FYI there's a pull request to resolve this you can try if you haven't resolved this already: #36

**Comment by emteknetnz** [comment]
I've created a temporary PR in queuedjobs to simulate updating the dependency in doorman so that queuedjobs tests run in travis with the new closure module https://github.com/symbiote/silverstripe-queuedjobs/pull/345
